import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../src/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        {children}
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      
      </body>
    </html>
  );
}

