import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../src/components/component/header/Header";
import Footer from "../src/components/component/footer/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <script dangerouslySetInnerHTML={{__html: "window.dataSavvyChatbotConfig = {chatbotId: '6610d3af7e39fab94eb5569e'}"}} /><script src='https://datasavvy.chat/js/embed-script.js' defer></script> */}
        <Header />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}