/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3ELYBzIGL7a
 */


export function aboutus() {
  return (
    (<div className="max-w-4xl mx-auto my-8 p-4 bg-white shadow rounded-lg">
      <div className="flex flex-col lg:flex-row">
        <div className="lg:w-1/4">
          <img
            alt="Placeholder"
            className="w-48 h-48 rounded-full mx-auto"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
            }}
            width="200" />
          <h2 className="mt-4 mb-2 text-xl font-semibold text-center">Amit Shah</h2>
          <p className="text-sm text-center text-gray-600">Shah in 2023</p>
          <div className="mt-4 p-2 border-t border-gray-200">
            <p className="text-sm font-semibold">34th Minister of Home Affairs</p>
            <p className="text-xs text-gray-600">Incumbent</p>
            <p className="text-xs text-gray-600">Assumed office 30 May 2019</p>
            <p className="text-sm font-semibold mt-2">Prime Minister</p>
            <p className="text-xs text-gray-600">Narendra Modi</p>
            <p className="text-sm font-semibold mt-2">Preceded by</p>
            <p className="text-xs text-gray-600">Rajnath Singh</p>
            <p className="text-sm font-semibold mt-2">1st Minister of Co-operation</p>
            <p className="text-xs text-gray-600">Incumbent</p>
            <p className="text-xs text-gray-600">Assumed office</p>
          </div>
        </div>
        <div className="lg:w-3/4 lg:pl-8">
          <p className="text-justify">
            Amit Anil Chandra Shah (born 22 October 1964) is an Indian politician who is currently serving as the 31st
            Minister of Home Affairs since 2019 and the 1st Minister of Co-operation of India since 2021. He served as
            the 10th President of the Bharatiya Janata Party (BJP) from 2014 to 2020. He has also served as chairman of
            the National Democratic Alliance (NDA) since 2014. He was elected to the lower house of Parliament, Lok
            Sabha, in the 2019 Indian general elections from Gandhinagar. Earlier, he had been elected as a member of
            the upper house of Parliament, Rajya Sabha, from Gujarat from 2017 to 2019.
          </p>
          <p className="text-justify mt-4">
            A chief strategist of the BJP, he is a close aide to Narendra Modi. He was also the member of the Gujarat
            Legislative Assembly from Naranpura from 2012 to 2017 and Sarkehj from 1997 to 2012 and the Minister of
            State for Home, Law and Justice, Prison, Border Security, Civil Defence, Excise, Home Guards, Transport,
            Prohibition, Gram Rakshak Dal, Police Housing, Legislative and Parliamentary Affairs, Government of Gujarat
            in the Modi ministry from 2002 to 2012. During his college days, Shah was a member of the Akhil Bharatiya
            Vidyarthi Parishad (ABVP), the student wing of the Rashtriya Swayamsevak Sangh (RSS). At the age of 18, he
            secured a position in the ABVP and joined the BJP in 1987.
          </p>
          <p className="text-justify mt-4">
            Shah was the BJP's in-charge for India's largest and politically most crucial state, Uttar Pradesh, during
            the 2014 Lok Sabha elections. The BJP-led NDA won 73 out of 80 seats. As a result, Shah rose to national
            prominence and was appointed as the party's national president in July 2014. He has played an organising and
            membership-promotional role in the elections of many states since 2014. In his initial two years, the BJP
            achieved success in Legislative Assembly elections in Maharashtra, Haryana, Jammu and Kashmir, Jharkhand and
            Assam but lost ground in Delhi and the large eastern state of Bihar in 2015.
          </p>
          <p className="text-justify mt-4">
            In 2017, he was partly credited with the party victories in Uttar Pradesh, Uttarakhand, Gujarat and Manipur,
            but the Akali-BJP alliance lost power in the larger Punjab election. In 2018, the party lost power in the
            states of Chhattisgarh, Rajasthan and Madhya Pradesh. A year later, the BJP won 303 seats to get a majority
            in the 2019 Indian general election under Shah's leadership.
          </p>
        </div>
      </div>
    </div>)
  );
}
